services:
  - type: web
    name: fletes-exus
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.backend:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
